### PR TITLE
Add "apipassword" to the example configuration

### PR DESCRIPTION
**Pull request by maartenpaauw**
Title says all.

### CODE REVIEW

**Comment by rafabene** [comment]
@aserramonner ?

**Comment by rafabene** [comment]
@maartenpaauw I've merged your PR in https://github.com/rafabene/MMM-HASS and I'll try to maintain this module. I'm making some improvements like adding prefix.

**Comment by rafabene** [comment]
Hi @maartenpaauw If you are not going to maintain it, please let me know.

**Comment by maartenpaauw** [comment]
@rafabene didn't you mean the owner?

**Comment by rafabene** [comment]
@maartenpaauw Right. Let me fix it.

**Pull request merged**
